### ISSUE TITLE
Fonts not show on macOS

### ISSUE THREAD

**Issue by thantez** [EvolveBeyond/NvPak#118]
Hey. I installed NvPak freshly on macOS and everything seems good except fonts. I also installed Nerd fonts, but nothing changed. What should I do? Also, my terminal is ITerm and I changed its font to Hack Nerd font mono and still there is the issue...

![image](https://github.com/EvolveBeyond/NvPak/assets/33148504/14f80f7e-7bc9-4271-8099-a5f78e2f3613)

**Comment by thantez** [comment]
I installed  ```font-fira-code-nerd-font font-fira-mono-nerd-font font-go-mono-nerd-font font-mononoki-nerd-font netron font-symbols-only-nerd-font``` and now some icons are properly shown but some of them not.

![Screenshot 2023-11-07 at 11 35 18 AM](https://github.com/EvolveBeyond/NvPak/assets/33148504/b1684ee2-6089-4319-90e9-9b7dca0965f7)

![Screenshot 2023-11-07 at 11 34 06 AM](https://github.com/EvolveBeyond/NvPak/assets/33148504/3014beef-1fed-4d3b-877c-e1105ba17621)

So my question is which font in nerd fonts should be installed?

**Comment by thantez** [comment]
Also, I reinstalled NvPak and still that little icon not shown.

**Comment by nooob-developer** [comment]
> Hey. I installed NvPak freshly on macOS and everything seems good except fonts. I also installed Nerd fonts, but nothing changed. What should I do? Also, my terminal is ITerm and I changed its font to Hack Nerd font mono and still there is the issue...
> 
> ![image](https://user-images.githubusercontent.com/33148504/280954408-14f80f7e-7bc9-4271-8099-a5f78e2f3613.png)


Unfortunately, I don't have access to macOS to test it directly. However, based on the description, it seems that there may be a problem with the correct configuration of fonts in NvPak on macOS.

But it works properly on Linux with the kitty terminal emulator and the latest font packages from the Arch repositories.
( ``ttf-font-awesome‍‍‍`` and ``noto-fonts-emoji`` ),
I recommend finding and installing the equivalent of the above packages on macOS

Arch packages are from the open source font projects Font Awesome and Noto Fonts, so you can search for macOS installers or binaries from those projects. We hope that installing them will solve NvPak font problems on macOS as well.

Let me know if you need help finding the right macOS font packages to install. While I can't test directly on macOS, I'd be happy to investigate them
