### ISSUE TITLE
wich one nerdfonts?

### ISSUE THREAD

**Issue by tahamokhtary** [EvolveBeyond/NvPak#120]
Hi, I want to install Nerd fonts in Fedora, but since it has several categories in its repository, I don't know which one to install for nvpak. please guide me.

**Comment by nooob-developer** [comment]
nvpak requires a font from the nerd fonts family.

It does not matter which specific font is used.

However, the fonts ‍‍‍```Fira Code``` and ```FantasqueSansMono Nerd Font‍‍``` have been tested before.

You can choose whichever of you prefer.
