### ISSUE TITLE
C++ support in nvpak?

### ISSUE THREAD

**Issue by pyrsth** [EvolveBeyond/NvPak#121]
Hello!
I want to use c++ in nvpak. Is there a way I can use LSP C++ in nvpak?

**Comment by nooob-developer** [comment]
To install the LSP server for C++, you can use the following command in nvpak:

‍‍`:LspInstall c++`

This will install and set up the LSP server for C++.You can also install LSP servers for other languages the same way. Just replace c++ with the language name in the :LspInstall command.
![20231222_20h42m03s_grim](https://github.com/EvolveBeyond/NvPak/assets/87908673/f6ff19d0-7031-4a74-b35f-a4266ccf5762)
![20231222_20h40m21s_grim](https://github.com/EvolveBeyond/NvPak/assets/87908673/b2b8f40d-83d5-406a-8c33-bdff1bef8516)

**Comment by pyrsth** [comment]
OK, THANKS.

**Comment by pyrsth** [comment]
now i reinstall nvpak and lsp install not found!
